/*
 * This file is generated by jOOQ.
 */
package org.acme.jooq;


import org.acme.jooq.tables.FlywaySchemaHistory;
import org.acme.jooq.tables.Users;


/**
 * Convenience access to all tables in manage_hotel.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>manage_hotel.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>manage_hotel.users</code>.
     */
    public static final Users USERS = Users.USERS;
}
